server:
  port: 7071

service.url:
  sure-pay: http://localhost:7070/v2/account

spring:
  servlet:
    multipart:
      enabled: true
  data:
    mongodb:
      #      commented for embedded mongo
      #      host: localhost
      #      port: 27017
      database: iban-name-check-database
      username: root
      password: rootpassword
      authentication-database: admin
      uri: mongodb://root:rootpassword@localhost:27017/iban-name-check-database?authSource=admin&authMechanism=SCRAM-SHA-1
  mongodb:
    embedded:
      version: 5.0.6

client.ssl:
  trustStore: truststore.jks
  trustStorePassword: password
  keyStore: keystore.jks
  keyStorePassword: password
  type: jks