server:
  port: 7071

spring:
  servlet:
    multipart:
      enabled: true
  data:
    mongodb:
      #      commented for embedded mongo
      #      host: localhost
      #      port: 27017
      database: iban-name-check-nosql-database
      username: root
      password: rootpassword
      authentication-database: admin
      uri: mongodb://root:rootpassword@localhost:27017/iban-name-check-nosql-database?authSource=admin&authMechanism=SCRAM-SHA-1
  mongodb:
    embedded:
      version: 5.0.6