server:
  port: 7071

logging:
  level:
    org.springframework.r2dbc: DEBUG

service.url:
  sure-pay: http://localhost:7070/v2/account

spring:
  application:
    name: iban-name-check-async
  servlet:
    multipart:
      enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/iban_name_check
    username: sashank
    password: password
#    pool:
#      enabled: true
#      initial-size: 5
#      max-size: 10

client.ssl:
  trustStore: truststore.jks
  trustStorePassword: password
  keyStore: keystore.jks
  keyStorePassword: password
  type: jks