---
version: "3.5"

services:
  mysql-container:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=iban-name-check
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    volumes:
      - mysql-data-container:/var/lib/mysql
      - ./mysql-data-container/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iban-name-check-network

  mongodb:
    image: mongo:6.0.2
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - iban-name-check-network

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
    networks:
      - iban-name-check-network

  postgres:
    container_name: postgres
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=sashank
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=iban_name_check
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/db

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/data/pgadmin

volumes:
  mysql-data-container:
    driver: local
  mongodb_data_container:
    driver: local
  postgres-data:
  pgadmin-data:

networks:
  iban-name-check-network: